// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxH0RzUwQwnRZVIJcgoUboCO4IQS62eUM',
    appId: '1:439740580389:web:27c5c10b247d9252c5f5cc',
    messagingSenderId: '439740580389',
    projectId: 'cmsc23-project-abramillano',
    authDomain: 'cmsc23-project-abramillano.firebaseapp.com',
    storageBucket: 'cmsc23-project-abramillano.appspot.com',
    measurementId: 'G-27RGE6D4NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqERyZaJL8YJDeqccKtYNq2l8IUTWuyGY',
    appId: '1:439740580389:android:ffc1b9059c09030ac5f5cc',
    messagingSenderId: '439740580389',
    projectId: 'cmsc23-project-abramillano',
    storageBucket: 'cmsc23-project-abramillano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKA6vH10oyZRorqBUUBjeAJ4ekYVMgsQ',
    appId: '1:439740580389:ios:af08f72354bc6cedc5f5cc',
    messagingSenderId: '439740580389',
    projectId: 'cmsc23-project-abramillano',
    storageBucket: 'cmsc23-project-abramillano.appspot.com',
    iosClientId: '439740580389-uhaevq06pu6fomu5vnrs6k19th0evcb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23ProjectRamillano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKA6vH10oyZRorqBUUBjeAJ4ekYVMgsQ',
    appId: '1:439740580389:ios:af08f72354bc6cedc5f5cc',
    messagingSenderId: '439740580389',
    projectId: 'cmsc23-project-abramillano',
    storageBucket: 'cmsc23-project-abramillano.appspot.com',
    iosClientId: '439740580389-uhaevq06pu6fomu5vnrs6k19th0evcb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23ProjectRamillano',
  );
}
